image:
  file: .gitpod.Dockerfile

tasks:
  - name: React
    init: npm install
    command: npm run start

  - name: Emulators
    command: |
      cd functions
      npm install
      cd ../
      mkdir /home/gitpod/.config/configstore
      echo $FIREBASE_CONFIG > /home/gitpod/.config/configstore/firebase-tools.json
      firebase functions:config:get > .runtimeconfig.json
      firebase emulators:start --only functions,firestore,storage,auth,pubsub --inspect-functions --import=./emulator_seeds

ports:
  - port: 3000
    onOpen: open-browser
  - port: 4000
    onOpen: open-browser
  - port: 4001-65536
    onOpen: ignore
